services:
  # Backend API Server
  - type: web
    name: vr-sports
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    routes:
      - type: redirect
        source: /
        destination: https://odds-frontend-j2pn.onrender.com
        statusCode: 301
    envVars:
      - key: NODE_ENV
        value: production
      - key: ODDS_API_KEY
        sync: false

  # Frontend React App
  - type: static
    name: my-react-frontend-021i
    env: node
    rootDir: client
    buildCommand: rm -rf src && npm install && npm run build
    staticPublishPath: ./build
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://odds-backend-4e9q.onrender.com
      - key: REACT_APP_SUPABASE_URL
        sync: false
      - key: REACT_APP_SUPABASE_ANON_KEY
        sync: false
